### ISSUE TITLE
User Auth

### ISSUE THREAD

**Issue by SanYung** [SanYung/Quack---A-Slack-Clone#2]
# User Auth
​
## Functionality
​
- [x] The main button with logo should link to `/`
- [x] Has working demo login
- [x] Smooth, bug free navigation
​
### Before Login
​
- [x] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [x] Errors should display for both `/signup` and `/login`.
- [x] Errors should clear when moving between `/signup` and `/login`.
- [x] Can sign up a user
- [x] Can sign in as a user
- [x] Can log out a user
- [x] Can't sign up with the same username/email
- [x] Pressing enter after filling out the session form should use the form data, not the demo user
​
### After Login
​
- [x] Should not be able to visit `/login` or `/signup`
- [x] Should be able to refresh the page and still be logged in
​
## Style
​
- [x] The site should look exactly like the actual site
- [x] All relevant elements should have `cursor: pointer` on hover
- [x] When errors are displayed, most elements should not move around the page (particularly input boxes)
- [ ] Remove Redux logger and all console.log()'s from production
​
## Seeds
- [x] Adequate and appropriate seeds

**Comment by jenvomo** [comment]
- [x] I would remove the border on buttons in the session form to make them look a little cleaner
- [x] Also maybe make the border on the input boxes a little less wide & a softer color?
- [x] Let's add a little bit of spacing between the input boxes and the buttons on the login/signup form so they elements aren't quite as squished together

**Comment by jenvomo** [comment]
Auth looks great @SanYung ! Just need to setup our middleware so logger doesn't show up in production.
